name: "Run Go Terraform Tests"
description: "Run a group of Go test suites against a given set of fixtures"
inputs:
  goVersion:
    description: "the version of Go used for the provided test suites"
    required: true
  terraformVersion:
    description: "the version of Terraform used for the provided fixtures"
    required: true
  fixtureDirectories:
    description: "an array of directories to run the test suites against"
    required: true
  testFileDirectories:
    description: "an array of directories containing the test suites for the fixtures you wish to test"
    required: true
  awsAccessKeyId:
    description: "your AWS Access Key ID for the fixtures"
    required: true
  awsSecretAccessKey:
    description: "your AWS Secret Access Key for the fixtures"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"